print('hello world')
print("hello world")
print("""hello world""")
print('''hello world''')
print('hello world', end='')
print()
print(None)
print("hello","world", sep="@")
print("hello 'world'")
print('hello "world"')
print("hello \"world\"")
print(r"hello \"world\"")
print("hello \n world")
a1 = 1
print(f"hello {a1}")